"""Generate docs/index.html from the live OpenAPI document.

The page is a single static file: no build step, no CDN, no framework. It is
regenerated by running this, so the endpoint list cannot drift from the code -
if a route is added or renamed, the docs change on the next run.

    python3 gen_docs.py > docs/index.html
"""
import json
import re
import sys
import urllib.request

SPEC_URL = "http://127.0.0.1:18742/api/v1/openapi.json"
OUT = "docs/index.html"

# Group the flat path list by its second segment, so 80 endpoints arrive as
# about a dozen sections instead of one undifferentiated wall. Order matters:
# the first matching prefix wins, so the narrow names come before the broad
# ones (wiki before games, jikan before anime).
GROUP_ORDER = [
    ("play", "Playable games"),
    ("jkt48", "JKT48"),
    ("mpl", "MPL Indonesia"),
    ("mlbb", "Mobile Legends"),
    ("liquid", "Liquid Death"),
    ("ai", "AI"),
    ("chatbotchatapp", "AI"),
    ("rewind", "AI"),
    ("fact", "AI"),
    ("jikan", "Anime and manga"),
    ("anime", "Anime and manga"),
    ("manga", "Anime and manga"),
    ("book", "Anime and manga"),
    ("wiki", "Game wikis"),
    ("game", "Game wikis"),
    ("tv", "TV and film"),
    ("tech", "News"),
    ("news", "News"),
    ("phone", "Phone numbers"),
    ("country", "Countries"),
]


def group_of(path):
    parts = path.strip("/").split("/")
    seg = parts[2] if len(parts) > 2 else "other"
    for key, label in GROUP_ORDER:
        if seg.startswith(key):
            return label
    return "Other"


def collect(spec):
    rows = []
    for path, ops in spec["paths"].items():
        op = ops.get("get") or {}
        params = op.get("parameters", [])
        query = [p["name"] for p in params if p.get("in") == "query"]
        rows.append({
            "path": path,
            "summary": op.get("summary", "").strip(),
            "public": not op.get("security"),
            "query": query,
        })
    return rows


def esc(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))


def example(path, query):
    """A copy-pasteable curl. Placeholders stay visible on purpose."""
    qs = "".join("&%s=…" % q for q in query[:2])
    return "curl -H 'Authorization: Bearer $TOKEN' \\\n     'https://your-host%s%s'" % (
        path, ("?" + qs[1:]) if qs else "")


# Raw, because the embedded CSS and JavaScript are full of backslashes that a
# regular string would try to interpret.
TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>%(title)s</title>
<style>
  :root {
    --bg:#0d1117; --panel:#161b22; --line:#30363d; --text:#e6edf3;
    --dim:#8b949e; --accent:#58a6ff; --open:#3fb950; --auth:#d29922;
  }
  * { box-sizing:border-box }
  body { margin:0; background:var(--bg); color:var(--text);
         font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif }
  header { padding:40px 24px 20px; max-width:1080px; margin:0 auto;
           border-bottom:1px solid var(--line) }
  h1 { margin:0 0 6px; font-size:28px; letter-spacing:-.4px }
  .sub { color:var(--dim); font-size:14px }
  .counts { margin-top:16px; display:flex; gap:10px; flex-wrap:wrap }
  .pill { background:var(--panel); border:1px solid var(--line);
          border-radius:20px; padding:5px 13px; font-size:13px }
  .pill b { color:var(--accent) }
  main { max-width:1080px; margin:0 auto; padding:0 24px 80px }
  .search { position:sticky; top:0; z-index:9; background:var(--bg);
            padding:18px 0 14px; border-bottom:1px solid var(--line);
            margin-bottom:8px }
  input { width:100%%; padding:12px 14px; font-size:15px;
          background:var(--panel); color:var(--text);
          border:1px solid var(--line); border-radius:8px }
  input:focus { outline:none; border-color:var(--accent) }
  h2 { margin:34px 0 4px; font-size:19px; letter-spacing:-.2px }
  h2 .n { color:var(--dim); font-weight:400; font-size:14px }
  details { border:1px solid var(--line); border-radius:8px;
            background:var(--panel); margin:8px 0 }
  summary { cursor:pointer; padding:12px 15px; list-style:none;
            display:flex; gap:12px; align-items:baseline; flex-wrap:wrap }
  summary::-webkit-details-marker { display:none }
  summary::before { content:"▸"; color:var(--dim); transition:transform .12s }
  details[open] summary::before { transform:rotate(90deg) }
  .verb { font:600 11px/1 ui-monospace,monospace; letter-spacing:.5px;
          color:var(--open); border:1px solid var(--line);
          border-radius:4px; padding:4px 6px }
  .path { font:13px ui-monospace,SFMono-Regular,Menlo,monospace;
          color:var(--accent); word-break:break-all }
  .desc { color:var(--dim); font-size:14px; flex:1; min-width:200px }
  .tag { font-size:11px; padding:3px 7px; border-radius:10px; white-space:nowrap }
  .tag.pub { color:var(--open); border:1px solid var(--open) }
  .tag.key { color:var(--auth); border:1px solid var(--auth) }
  .body { padding:0 15px 15px 40px; border-top:1px solid var(--line) }
  table { width:100%%; border-collapse:collapse; font-size:13px; margin:10px 0 }
  td,th { text-align:left; padding:5px 9px; border-bottom:1px solid var(--line);
          vertical-align:top }
  th { color:var(--dim); font-weight:500 }
  code { font:12.5px ui-monospace,SFMono-Regular,Menlo,monospace;
         background:#0d1117; border:1px solid var(--line);
         border-radius:5px; padding:2px 6px }
  pre { background:#0d1117; border:1px solid var(--line); border-radius:8px;
        padding:13px 15px; overflow-x:auto; margin:11px 0 }
  pre code { background:none; border:0; padding:0 }
  button { background:var(--panel); color:var(--text); cursor:pointer;
           border:1px solid var(--line); border-radius:6px;
           padding:5px 11px; font-size:12.5px; margin-top:6px }
  button:hover { border-color:var(--accent); color:var(--accent) }
  .out { background:#0d1117; border:1px solid var(--line); border-radius:8px;
         padding:12px 14px; font:12.5px ui-monospace,monospace;
         white-space:pre-wrap; word-break:break-word; margin-top:10px;
         max-height:340px; overflow:auto; display:none }
  .none { padding:40px 0; color:var(--dim); text-align:center }
  .connect { padding:20px 0 4px;
             display:flex; gap:10px; flex-wrap:wrap; align-items:center }
  .connect input { flex:1; min-width:230px }
  .connect .note { width:100%%; color:var(--dim); font-size:12.5px }
  footer { max-width:1080px; margin:0 auto; padding:22px 24px 60px;
           color:var(--dim); font-size:13px; border-top:1px solid var(--line) }
  a { color:var(--accent) }
</style>
</head>
<body>
<header>
  <h1>%(title)s</h1>
  <div class="sub">%(description)s</div>
  <div class="counts">
    <span class="pill"><b>%(total)d</b> endpoints</span>
    <span class="pill"><b>%(ngroups)d</b> groups</span>
    <span class="pill"><b>%(npublic)d</b> routes open without a token</span>
    <span class="pill"><b>0</b> third-party dependencies</span>
  </div>
</header>
<main>
  <div class="connect">
    <input id="base" placeholder="API base URL, e.g. http://your-host:18742"
           autocomplete="off" spellcheck="false">
    <input id="tok" type="password" placeholder="Bearer token (optional for public routes)"
           autocomplete="off" spellcheck="false">
    <button id="save" type="button">Save</button>
    <div class="note">Saved in this browser only. The docs page is static and
      knows nothing about your server; "Try it" needs both values filled in
      unless the route is marked as needing no key.</div>
  </div>
  <div class="search">
    <input id="q" placeholder="Search paths, descriptions and query parameters…"
           autocomplete="off" spellcheck="false">
  </div>
  <div id="list">%(body)s</div>
  <div class="none" id="empty" style="display:none">Nothing matches that.</div>
</main>
<footer>
  <div>Generated from the live OpenAPI document, so it cannot drift from the
       code. Pure standard library: no framework, no CDN, no build step.</div>
  <div style="margin-top:9px">Machine-readable: <a href="/api/v1/catalog">/api/v1/catalog</a>
       · <a href="/api/v1/openapi.json">/api/v1/openapi.json</a></div>
</footer>
<script>
// "Try it" cannot assume it is served by the API: this page is static and may
// live on GitHub Pages while the API runs elsewhere. So the operator supplies
// the base URL once, and both values stay in this browser.
const baseBox = document.getElementById('base');
const tokBox = document.getElementById('tok');
const store = {
  get: (k) => localStorage.getItem('apibot_' + k) || '',
  set: (k, v) => localStorage.setItem('apibot_' + k, v),
};
baseBox.value = store.get('base');
tokBox.value = store.get('token');
document.getElementById('save').addEventListener('click', () => {
  store.set('base', baseBox.value.trim().replace(/\/+$/, ''));
  store.set('token', tokBox.value.trim());
  tokBox.value = store.get('token');
});

const box = document.getElementById('q');
const items = [...document.querySelectorAll('#list details')];
const groups = [...document.querySelectorAll('#list h2')];
const empty = document.getElementById('empty');

function run() {
  const v = box.value.trim().toLowerCase();
  let shown = 0;
  for (const g of groups) g.style.display = 'none';
  for (const d of items) {
    // textContent covers the summary, the parameters and the curl example,
    // so searching "dice=2d6" or "pity" finds the route that mentions it
    const hit = !v || d.textContent.toLowerCase().includes(v);
    d.style.display = hit ? '' : 'none';
    if (hit) shown++;
    if (v && hit) d.open = true;
  }
  // a heading is only useful if the group under it has a visible member
  for (const g of groups) {
    let n = g.nextElementSibling, any = false;
    while (n && n.tagName !== 'H2') {
      if (n.style.display !== 'none') { any = true; break; }
      n = n.nextElementSibling;
    }
    g.style.display = any ? '' : 'none';
  }
  empty.style.display = shown ? 'none' : '';
  document.getElementById('list').style.display = shown ? '' : 'none';
}
box.addEventListener('input', run);
run();

document.addEventListener('click', async (e) => {
  const btn = e.target.closest('[data-try]');
  if (!btn) return;
  const out = btn.parentElement.querySelector('.out');
  const base = store.get('base');
  btn.textContent = 'requesting…';
  out.style.display = 'block';
  out.textContent = '';
  if (!base) {
    out.textContent = 'Set the API base URL above first.';
    btn.textContent = 'Try it';
    return;
  }
  const headers = {};
  const token = store.get('token');
  if (token) headers['Authorization'] = 'Bearer ' + token;
  try {
    const res = await fetch(base + btn.dataset.try, {headers});
    const body = await res.text();
    out.textContent = res.status + ' ' + res.statusText + '\n\n' +
                      body.slice(0, 4000);
  } catch (err) {
    out.textContent = 'failed: ' + err;
  }
  btn.textContent = 'Try it';
});
</script>
</body>
</html>
"""


def main():
    with urllib.request.urlopen(SPEC_URL, timeout=20) as fh:
        spec = json.loads(fh.read().decode())
    rows = collect(spec)

    groups = {}
    for row in rows:
        groups.setdefault(group_of(row["path"]), []).append(row)

    out = []
    for label, entries in groups.items():
        entries.sort(key=lambda r: r["path"])
        out.append("<h2>%s <span class=\"n\">%d</span></h2>" % (esc(label), len(entries)))
        for row in entries:
            params = ""
            if row["query"]:
                params = ("<table><tr><th>query</th><th>" +
                          ", ".join("<code>%s</code>" % esc(q) for q in row["query"]) +
                          "</td></tr></table>")
            tag = ('<span class="tag pub">no key</span>' if row["public"]
                   else '<span class="tag key">bearer token</span>')
            out.append(
                "<details><summary>"
                '<span class="verb">GET</span>'
                '<span class="path">%s</span>'
                '<span class="desc">%s</span>%s'
                "</summary><div class=\"body\">%s"
                "<pre><code>%s</code></pre>"
                '<button data-try="%s">Try it</button>'
                '<div class="out"></div>'
                "</div></details>"
                % (esc(row["path"]), esc(row["summary"]), tag, params,
                   esc(example(row["path"], row["query"])),
                   esc(row["path"])))

    html = TEMPLATE % {
        "title": spec["info"]["title"],
        "description": spec["info"]["description"],
        "total": len(rows),
        "ngroups": len(groups),
        "npublic": sum(1 for r in rows if r["public"]),
        "body": "\n".join(out),
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(html)
    print("wrote %s: %d endpoints in %d groups, %.1f KB"
          % (OUT, len(rows), len(groups), len(html) / 1024), file=sys.stderr)


if __name__ == "__main__":
    main()
