"""Generate docs/index.html from the live OpenAPI document.

The page is a single static file: no build step, no CDN, no framework. It is
regenerated by running this, so the endpoint list cannot drift from the code -
if a route is added or renamed, the docs change on the next run.

    python3 gen_docs.py > docs/index.html
"""
import json
import re
import sys
import urllib.request

SPEC_URL = "http://127.0.0.1:18742/api/v1/openapi.json"
OUT = "docs/index.html"

# Group the flat path list by its second segment, so 80 endpoints arrive as
# about a dozen sections instead of one undifferentiated wall. Order matters:
# the first matching prefix wins, so the narrow names come before the broad
# ones (wiki before games, jikan before anime).
GROUP_ORDER = [
    ("play", "Playable games"),
    ("jkt48", "JKT48"),
    ("mpl", "MPL Indonesia"),
    ("mlbb", "Mobile Legends"),
    ("liquid", "Liquid Death"),
    ("ai", "AI"),
    ("chatbotchatapp", "AI"),
    ("rewind", "AI"),
    ("fact", "AI"),
    ("jikan", "Anime and manga"),
    ("anime", "Anime and manga"),
    ("manga", "Anime and manga"),
    ("book", "Anime and manga"),
    ("wiki", "Game wikis"),
    ("game", "Game wikis"),
    ("tv", "TV and film"),
    ("tech", "News"),
    ("news", "News"),
    ("phone", "Phone numbers"),
    ("country", "Countries"),
]


def group_of(path):
    parts = path.strip("/").split("/")
    seg = parts[2] if len(parts) > 2 else "other"
    for key, label in GROUP_ORDER:
        if seg.startswith(key):
            return label
    return "Other"


def collect(spec):
    rows = []
    for path, ops in spec["paths"].items():
        op = ops.get("get") or {}
        params = op.get("parameters", [])
        query = [p["name"] for p in params if p.get("in") == "query"]
        rows.append({
            "path": path,
            "summary": op.get("summary", "").strip(),
            "public": not op.get("security"),
            "query": query,
        })
    return rows


def esc(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))


def example(path, query):
    """A copy-pasteable curl. Placeholders stay visible on purpose."""
    qs = "".join("&%s=…" % q for q in query[:2])
    return "curl -H 'Authorization: Bearer $TOKEN' \\\n     'https://your-host%s%s'" % (
        path, ("?" + qs[1:]) if qs else "")


TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>%(title)s</title>
<style>
  :root {
    --bg:#0a0e14; --panel:#11161d; --panel2:#161d26; --line:#232c38;
    --text:#e8eef6; --dim:#8b98a8; --faint:#5c6b7a;
    --accent:#5aa2ff; --accent2:#3d7ddb; --open:#3fb950; --auth:#e3b341;
    --radius:10px;
  }
  * { box-sizing:border-box }
  html { scroll-behavior:smooth }
  body { margin:0; background:var(--bg); color:var(--text);
    font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
    -webkit-font-smoothing:antialiased }
  a { color:var(--accent); text-decoration:none }
  a:hover { text-decoration:underline }

  /* ---- layout: fixed sidebar + scrolling content ---- */
  .wrap { display:grid; grid-template-columns:264px minmax(0,1fr);
          max-width:1400px; margin:0 auto; gap:0 }
  aside { position:sticky; top:0; align-self:start;
          max-height:100vh; overflow-y:auto; overscroll-behavior:contain;
          padding:26px 20px 40px; border-right:1px solid var(--line) }
  /* the group list is the only part allowed to scroll away; the identity
     fields at the top stay put, so scroll hides nav links, never the input */
  aside > .stats, aside > .field { position:sticky; top:0;
          background:var(--bg); z-index:1 }
  .brand { font-size:19px; font-weight:650; letter-spacing:-.3px;
           margin:0 0 2px; display:flex; align-items:center; gap:8px }
  .brand .dot { width:8px; height:8px; border-radius:50%%;
                background:var(--open); box-shadow:0 0 8px var(--open) }
  .tagline { color:var(--dim); font-size:12.5px; margin:0 0 18px }
  .stats { display:grid; grid-template-columns:1fr 1fr; gap:8px;
           margin-bottom:20px }
  .stat { background:var(--panel); border:1px solid var(--line);
          border-radius:var(--radius); padding:9px 11px }
  .stat b { display:block; font-size:19px; color:var(--accent);
            line-height:1.2; letter-spacing:-.4px }
  .stat span { color:var(--faint); font-size:11px; text-transform:uppercase;
               letter-spacing:.5px }

  .field { margin-bottom:10px }
  .field label { display:block; color:var(--dim); font-size:11.5px;
                 margin-bottom:4px; text-transform:uppercase;
                 letter-spacing:.5px }
  input { width:100%%; padding:9px 11px; font-size:13.5px;
          background:var(--panel); color:var(--text);
          border:1px solid var(--line); border-radius:8px;
          font-family:ui-monospace,SFMono-Regular,Menlo,monospace }
  input:focus { outline:none; border-color:var(--accent);
                box-shadow:0 0 0 3px rgba(90,162,255,.13) }
  input::placeholder { color:var(--faint) }
  .row { display:flex; gap:8px }
  .row input { flex:1; min-width:0 }
  button { background:var(--panel2); color:var(--text); cursor:pointer;
           border:1px solid var(--line); border-radius:8px; padding:8px 12px;
           font-size:13px; font-family:inherit; transition:.12s }
  button:hover { border-color:var(--accent); color:var(--accent) }
  button.primary { background:var(--accent2); border-color:var(--accent2);
                   color:#fff; font-weight:600 }
  button.primary:hover { background:var(--accent); border-color:var(--accent) }

  nav { margin-top:22px; border-top:1px solid var(--line); padding-top:14px }
  nav a { display:flex; justify-content:space-between; align-items:baseline;
          gap:8px; padding:6px 9px; border-radius:7px; color:var(--dim);
          font-size:13.5px }
  nav a:hover { background:var(--panel); color:var(--text);
                text-decoration:none }
  nav a .c { color:var(--faint); font-size:11.5px;
             font-family:ui-monospace,monospace }
  nav .cap { color:var(--faint); font-size:11px; text-transform:uppercase;
             letter-spacing:.6px; margin:0 9px 5px }

  main { padding:30px 34px 90px; min-width:0 }
  .searchbar { position:sticky; top:0; z-index:9; background:var(--bg);
               padding:0 0 16px; margin-bottom:6px;
               display:flex; gap:10px; align-items:center }
  .searchbar input { font-size:15px; padding:11px 14px }
  .kbd { color:var(--faint); font-size:11px; white-space:nowrap }
  kbd { background:var(--panel2); border:1px solid var(--line);
        border-bottom-width:2px; border-radius:5px; padding:2px 6px;
        font:11px ui-monospace,monospace; color:var(--dim) }

  section { scroll-margin-top:64px }
  h2 { margin:34px 0 12px; font-size:17px; letter-spacing:-.2px;
       display:flex; align-items:baseline; gap:9px }
  h2::before { content:""; width:3px; height:15px; background:var(--accent);
               border-radius:2px }
  h2 .n { color:var(--faint); font-weight:400; font-size:13px }

  details { background:var(--panel); border:1px solid var(--line);
            border-radius:var(--radius); margin-bottom:6px;
            overflow:hidden; transition:border-color .12s }
  details:hover { border-color:#31405180 }
  details[open] { border-color:var(--accent2) }
  summary { cursor:pointer; padding:11px 14px; list-style:none;
            display:flex; gap:11px; align-items:center }
  summary::-webkit-details-marker { display:none }
  summary:hover { background:#ffffff06 }
  .caret { color:var(--faint); font-size:10px; transition:transform .14s;
           flex:0 0 auto }
  details[open] .caret { transform:rotate(90deg) }
  .verb { font:600 10px/1 ui-monospace,monospace; letter-spacing:.5px;
          color:var(--open); background:#3fb95018; border:1px solid #3fb95040;
          border-radius:4px; padding:4px 6px; flex:0 0 auto }
  .path { font:13px ui-monospace,SFMono-Regular,Menlo,monospace;
          color:var(--accent); word-break:break-all; flex:0 1 auto }
  .desc { color:var(--dim); font-size:13.5px; flex:1; min-width:0;
          display:-webkit-box; -webkit-line-clamp:2; -webkit-box-orient:vertical;
          overflow:hidden }
  .tag { font-size:10.5px; padding:3px 7px; border-radius:10px;
         white-space:nowrap; flex:0 0 auto }
  .tag.pub { color:var(--open); border:1px solid #3fb95050 }
  .tag.key { color:var(--auth); border:1px solid #e3b34150 }

  .body { padding:14px 16px 16px 42px; border-top:1px solid var(--line);
          background:#0000001a }
  .kv { display:grid; grid-template-columns:74px minmax(0,1fr); gap:4px 12px;
        font-size:13px; margin:0 0 12px }
  .kv dt { color:var(--faint); font-size:11.5px; text-transform:uppercase;
           letter-spacing:.4px; padding-top:3px }
  .kv dd { margin:0 }
  code { font:12.5px ui-monospace,SFMono-Regular,Menlo,monospace;
         background:#0a0e14; border:1px solid var(--line);
         border-radius:5px; padding:2px 6px; color:var(--text) }
  .qtag { display:inline-block; margin:0 4px 4px 0 }
  pre { background:#080c11; border:1px solid var(--line); border-radius:8px;
        padding:12px 14px; overflow-x:auto; margin:0 0 10px; position:relative }
  pre code { background:none; border:0; padding:0; color:#c9d6e4;
             font-size:12.5px; line-height:1.65 }
  .copy { position:absolute; top:7px; right:7px; padding:3px 9px;
          font-size:11px; opacity:0; transition:.12s }
  pre:hover .copy { opacity:1 }
  .out { background:#080c11; border:1px solid var(--line); border-radius:8px;
         padding:12px 14px; font:12.5px ui-monospace,monospace;
         white-space:pre-wrap; word-break:break-word; margin-top:10px;
         max-height:360px; overflow:auto; display:none;
         color:#b9c9d8 }
  .acts { display:flex; gap:8px; align-items:center }
  .none { padding:60px 0; color:var(--faint); text-align:center }

  footer { margin-top:44px; padding-top:20px; border-top:1px solid var(--line);
           color:var(--faint); font-size:12.5px; display:flex;
           flex-wrap:wrap; gap:6px 18px }

  @media (max-width:900px) {
    .wrap { grid-template-columns:1fr }
    aside { position:static; height:auto; border-right:0;
            border-bottom:1px solid var(--line); padding:20px 18px 16px }
    .stats { grid-template-columns:repeat(4,1fr) }
    nav { display:flex; flex-wrap:wrap; gap:4px }
    nav .cap { width:100%% }
    main { padding:20px 18px 70px }
    .desc { white-space:normal }
    summary { flex-wrap:wrap }
  }
  @media (max-width:480px) {
    .stats { grid-template-columns:repeat(2,1fr) }
    .row { flex-wrap:wrap }
    .kbd { display:none }
  }
</style>
</head>
<body>
<div class="wrap">
<aside>
  <h1 class="brand"><span class="dot"></span>%(title)s</h1>
  <p class="tagline">No upstream API keys &middot; pure standard library</p>

  <div class="stats">
    <div class="stat"><b>%(total)d</b><span>endpoints</span></div>
    <div class="stat"><b>%(ngroups)d</b><span>groups</span></div>
    <div class="stat"><b>%(npublic)d</b><span>open</span></div>
    <div class="stat"><b>0</b><span>deps</span></div>
  </div>

  <div class="field">
    <label for="base">API base URL</label>
    <input id="base" placeholder="http://host:18742" autocomplete="off"
           spellcheck="false">
  </div>
  <div class="field">
    <label for="tok">Bearer token</label>
    <div class="row">
      <input id="tok" type="password" placeholder="optional"
             autocomplete="off" spellcheck="false">
      <button id="save" type="button">Save</button>
    </div>
  </div>

  <nav>
    <p class="cap">Groups</p>
    %(nav)s
  </nav>
</aside>

<main>
  <div class="searchbar">
    <input id="q" placeholder="Search endpoints, parameters, descriptions…"
           autocomplete="off" spellcheck="false">
    <span class="kbd"><kbd>/</kbd> focus</span>
  </div>
  <div id="list">%(body)s</div>
  <div class="none" id="empty" style="display:none">No endpoint matches that.</div>
</main>
</div>

<footer>
  <span>Generated from the live OpenAPI document, so it cannot drift from the code.</span>
  <span>Machine-readable: <a href="/api/v1/catalog">/api/v1/catalog</a> &middot;
        <a href="/api/v1/openapi.json">openapi.json</a></span>
</footer>

<script>
// This page is static and may be published somewhere the API is not
// (GitHub Pages vs a self-hosted ApiBot are different origins), so the
// operator supplies the base URL once and it stays in this browser only.
const store = {
  get: (k) => localStorage.getItem('apibot_' + k) || '',
  set: (k, v) => localStorage.setItem('apibot_' + k, v),
};
const baseBox = document.getElementById('base');
const tokBox = document.getElementById('tok');
baseBox.value = store.get('base');
tokBox.value = store.get('token');
document.getElementById('save').addEventListener('click', () => {
  store.set('base', baseBox.value.trim().replace(/\/+$/, ''));
  store.set('token', tokBox.value.trim());
  tokBox.value = store.get('token');
  flash(document.getElementById('save'), 'Saved');
});

function flash(btn, msg) {
  const was = btn.textContent;
  btn.textContent = msg;
  setTimeout(() => { btn.textContent = was; }, 1100);
}

const box = document.getElementById('q');
const items = [...document.querySelectorAll('#list details')];
const heads = [...document.querySelectorAll('#list section')];
const empty = document.getElementById('empty');

function run() {
  const v = box.value.trim().toLowerCase();
  let shown = 0;
  for (const sec of heads) {
    let any = false;
    for (const d of sec.querySelectorAll('details')) {
      // textContent covers the summary, the parameters and the curl example,
      // so "2d6" finds the dice route through its parameter, not just its name
      const hit = !v || d.textContent.toLowerCase().includes(v);
      d.style.display = hit ? '' : 'none';
      if (hit) { any = true; shown++; }
      if (v && hit) d.open = true;
    }
    sec.style.display = any ? '' : 'none';
  }
  empty.style.display = shown ? '' : 'none';
  document.getElementById('list').style.display = shown ? '' : 'none';
}
box.addEventListener('input', run);
document.addEventListener('keydown', (e) => {
  if (e.key === '/' && document.activeElement !== box) {
    e.preventDefault(); box.focus(); box.select();
  } else if (e.key === 'Escape' && document.activeElement === box) {
    box.value = ''; box.blur(); run();
  }
});
run();

document.addEventListener('click', async (e) => {
  const cp = e.target.closest('[data-copy]');
  if (cp) {
    const text = cp.closest('pre').querySelector('code').textContent;
    try { await navigator.clipboard.writeText(text); flash(cp, 'Copied'); }
    catch { flash(cp, 'Ctrl+C'); }
    return;
  }
  const btn = e.target.closest('[data-try]');
  if (!btn) return;
  const out = btn.parentElement.querySelector('.out');
  const base = store.get('base');
  btn.textContent = 'requesting…';
  out.style.display = 'block';
  out.textContent = '';
  if (!base) { out.textContent = 'Set the API base URL in the sidebar first.'; btn.textContent = 'Try it'; return; }
  const headers = {};
  const token = store.get('token');
  if (token) headers['Authorization'] = 'Bearer ' + token;
  try {
    const res = await fetch(base + btn.dataset.try, {headers});
    out.textContent = res.status + ' ' + res.statusText + '\n\n' + (await res.text()).slice(0, 4000);
  } catch (err) {
    out.textContent = 'failed: ' + err;
  }
  btn.textContent = 'Try it';
});
</script>
</body>
</html>
"""


def slug(label):
    return "g-" + "".join(c if c.isalnum() else "-" for c in label.lower()).strip("-")


def main():
    with urllib.request.urlopen(SPEC_URL, timeout=20) as fh:
        spec = json.loads(fh.read().decode())
    rows = collect(spec)

    groups = {}
    for row in rows:
        groups.setdefault(group_of(row["path"]), []).append(row)
    # Biggest groups first: on a docs page the things people came for are the
    # playable games and the AI routes, not the alphabetically-early strays.
    order = sorted(groups.items(), key=lambda kv: (-len(kv[1]), kv[0]))

    body, nav = [], []
    for label, entries in order:
        entries.sort(key=lambda r: r["path"])
        anchor = slug(label)
        nav.append('<a href="#%s">%s<span class="c">%d</span></a>'
                   % (anchor, esc(label), len(entries)))
        body.append('<section id="%s">' % anchor)
        body.append("<h2>%s<span class=\"n\">%d</span></h2>" % (esc(label), len(entries)))
        for row in entries:
            params = ""
            if row["query"]:
                chips = "".join('<code class="qtag">%s</code>' % esc(q)
                                for q in row["query"])
                params = '<dl class="kv"><dt>query</dt><dd>%s</dd></dl>' % chips
            tag = ('<span class="tag pub">no key</span>' if row["public"]
                   else '<span class="tag key">token</span>')
            body.append(
                "<details><summary>"
                '<span class="caret">\u25b8</span>'
                '<span class="verb">GET</span>'
                '<span class="path">%s</span>'
                '<span class="desc" title="%s">%s</span>%s'
                "</summary><div class=\"body\">%s"
                "<pre><button class=\"copy\" data-copy>Copy</button>"
                "<code>%s</code></pre>"
                '<div class="acts">'
                '<button class="primary" data-try="%s">Try it</button>'
                "</div>"
                '<div class="out"></div>'
                "</div></details>"
                % (esc(row["path"]), esc(row["summary"]),
                   esc(row["summary"]), tag, params,
                   esc(example(row["path"], row["query"])),
                   esc(row["path"])))
        body.append("</section>")

    html = TEMPLATE % {
        "title": spec["info"]["title"],
        "total": len(rows),
        "ngroups": len(groups),
        "npublic": sum(1 for r in rows if r["public"]),
        "nav": "\n    ".join(nav),
        "body": "\n".join(body),
    }
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(html)
    print("wrote %s: %d endpoints in %d groups, %.1f KB"
          % (OUT, len(rows), len(groups), len(html) / 1024), file=sys.stderr)


if __name__ == "__main__":
    main()
